### ISSUE TITLE
bug: fail to create oapp with create-lz-oapp@latest

### ISSUE THREAD

**Issue by zouguangxian** [LayerZero-Labs/devtools#315]
**Describe the bug**

**To Reproduce**

```shell
❯ npx create-lz-oapp@latest
```

**Expected behavior**
This command will create of a new omnichain application project, set up the necessary environment and dependencies.

**Screenshots**
```
✔ Where do you want to start your project? … ./my-lz-oapp
✔ Which example would you like to use as a starting point? › OFT
✔ What package manager would you like to use in your project? › pnpm

Will create a project in ./my-lz-oapp directory (/Users/gx/temp/demo/my-lz-oapp)
Will use the OFT example
Will use pnpm to install dependencies

✔ Do you want to continue? … yes
𐄂 Getting example source code
  Error: Unknown error during example cloning
○ Installing dependencies

```

**Environment (please complete the following information):**
```
❯ uname -a
Darwin MacBook-Pro-3.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64
❯ node --version           
v18.12.0
❯ which pnpm     
/Users/gx/.nvm/versions/node/v18.12.0/bin/pnpm
```

- OS: macOS
- OS Version: 14.0
- VM: Node
- VM Version: 18.12.0

**Additional context**

**Comment by janjakubnanista** [comment]
Hey @zouguangxian!

We are still in a process to make the functionality fully available.

#314 contains end-user test suite which we use to verify that the tools and examples will work for the developers
#312 will be merged after that and will enable developers to access the packages

Stay tuned, not too long before that happens!

**Comment by janjakubnanista** [comment]
@zouguangxian you should be able to run the command successfully now, packages have been published!

**Comment by janjakubnanista** [comment]
The installation should now work fine, please reopen this issue if experiencing any problems! Thanks for the feedback!
