### ISSUE TITLE
bug: [bug summary]

### ISSUE THREAD

**Issue by parzivalishan** [LayerZero-Labs/devtools#418]
there is a typo while running the following command : npx create-lz-oapp@latest

instead of dapp it shows deap

**Comment by parzivalishan** [comment]
$ npm install @layerzerolabs/lz-evm-oapp-v2

npm WARN deprecated zksync-web3@0.14.4: This package has been deprecated in favor of zksync-ethers@5.0.0

**Comment by cl3pl4t3** [comment]
0

**Comment by janjakubnanista** [comment]
Hello there! We are aware of the deprecation of the zksync library, however, it's a transitive dependency over which we don't have control
