### ISSUE TITLE
🧹 Replace hardhat node with anvil in CI/CD

### ISSUE THREAD

**Issue by janjakubnanista** [LayerZero-Labs/devtools#487]
**Is your feature request related to a problem? Please describe.**

Currently the EVM nodes that support the test runs are `hardhat` nodes. This slows down the pipeline in two ways:

- The docker container needs to be built for the nodes to start
- The node itself is lower performance than `anvil`

**Describe the solution you'd like**

Replace the `test-evm-node` package and its usage with `anvil`-based node implementation

**Comment by ravinagill15** [comment]
Turns out Anvil is much slower that Hardhat, closing issue
