### ISSUE TITLE
bug: No param `baseGas` in `DstConfigParam` struct

### ISSUE THREAD

**Issue by abhi3700** [LayerZero-Labs/devtools#539]
**Describe the bug**
After `$ npx create-lz-oapp@latest`, I faced error when compiling.

**To Reproduce**

1. `$ npx create-lz-oapp@latest` to create a project.
2. Select OFT option
3. `$ pnpm compile` gives this error:
```sh
$ pnpm compile

> @layerzerolabs/oft-example@0.2.2 compile /Users/abhi3700/F/coding/github_repos/subspace/layerzero-demo2/my-lz-oapp
> $npm_execpath run compile:forge && $npm_execpath run compile:hardhat


> @layerzerolabs/oft-example@0.2.2 compile:forge /Users/abhi3700/F/coding/github_repos/subspace/layerzero-demo2/my-lz-oapp
> forge build

[⠊] Compiling...
[⠔] Compiling 122 files with 0.8.22
[⠒] Solc 0.8.22 finished in 439.99ms
Error:
Compiler run failed:
Error (9582): Member "baseGas" not found or not visible after argument-dependent lookup in struct IExecutor.DstConfigParam memory.
  --> node_modules/@layerzerolabs/test-devtools-evm-foundry/contracts/mocks/ExecutorMock.sol:46:17:
   |
46 |                 param.baseGas,
   |                 ^^^^^^^^^^^^^

 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

**Expected behavior**
It should have compiled successfully. Clearly, the parameter `baseGas` is not present in `DstConfigParam` struct in `IExecutor.sol`. [Screenshot attached](https://github.com/LayerZero-Labs/devtools/assets/16472948/73b4342c-3210-462d-9c52-a36badb4ccc6)

**Screenshots**
![image](https://github.com/LayerZero-Labs/devtools/assets/16472948/162dc296-b790-4df6-acae-9fb3630d5249)
![image](https://github.com/LayerZero-Labs/devtools/assets/16472948/73b4342c-3210-462d-9c52-a36badb4ccc6)

**Environment (please complete the following information):**

- OS: macOS
- OS Sonoma 14.4.1
- VM: node
- VM Version: v18.18.0

**Additional context**
None

**Comment by janjakubnanista** [comment]
Updating your `@layerzerolabs` dependencies will resolve the issue. For a new oapp, running `npx create-lz-oapp@latest` will result in a working project.
