### ISSUE TITLE
Unable to build OFT based token contract

### ISSUE THREAD

**Issue by voxil1010** [LayerZero-Labs/devtools#821]
**Describe the bug**
I am trying to use devtools in my foundry project. When i build my contracts I get:

```
Error (7576): Undeclared identifier.
   --> lib/devtools/packages/test-devtools-evm-foundry/contracts/mocks/PriceFeedMock.sol:184:16:
    |
184 |         revert LZ_PriceFeed_NotAnOPStack(l2Eid);
```
Is it some versioning issue on my end? I tried to check [LayerZero-v2](https://github.com/LayerZero-Labs/LayerZero-v2/blob/main/packages/layerzero-v2/evm/messagelib/contracts/interfaces/ILayerZeroPriceFeed.sol) but cant seem to find error declared there.

**To Reproduce**

1. Create a new foundry project.
2. Install forge install https://github.com/LayerZero-Labs/devtools
3. forge install https://github.com/LayerZero-Labs/layerzero-v2
4. Then create an OFT standard token.
5. build the project

**Expected behavior**
I think it should build it sucessfully without any errors.

**Environment (please complete the following information):**

- OS: maxOS
- forge version: forge 0.2.0 (a4d79ac 2024-05-10T00:18:07.559888000Z)

**Comment by DanL0** [comment]
https://github.com/LayerZero-Labs/layerzero-v2 package isn't recommended to use for new projects right now.

Please follow this guide: https://docs.layerzero.network/v2/developers/evm/create-lz-oapp/start
